# Common configuration for all releases of Fedora
.fedora: &fedora
    # Install the Red Hat IT Root CA
    before_script:
        - curl --insecure https://password.corp.redhat.com/RH-IT-Root-CA.crt -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
        - update-ca-trust

    script:
        # Install dnf support for copr and rhcopr
        - dnf install dnf-plugins-core -y
        - dnf config-manager --add-repo https://copr.devel.redhat.com/coprs/rhcopr-project/toolset/repo/fedora-${VERSION}/rhcopr-project-toolset-fedora-${VERSION}.repo
        - dnf install make rhcopr -y

        # Enable given (rh)copr repositories
        - if [[ ! -v NO_DIVINE ]]; then dnf copr enable lzaoral/Divine -y; fi
        - if [[ ! -v NO_SYMBIOTIC ]]; then dnf copr enable jamartis/symbiotic -y; fi
        - dnf copr enable kdudka/predator -y
        - dnf copr enable redhat/vmihalko/cbmc_utils -y
        - dnf copr enable redhat/kdudka/csdiff -y

        # Update the system
        - dnf update -y
        - DNF_OPTS=-y make install-deps

        # first run only cheap tests, so that we can report failures sooner
        - CTEST_OPTS='-LE EXPENSIVE' make check

        # try single-c/sync.sh script
        - SYNC_EXISTING_ONLY=1 tests/single-c/sync.sh -LE EXPENSIVE
        - CTEST_OPTS='-LE EXPENSIVE' make check

        # then run all expensive tests
        - CTEST_OPTS='-L EXPENSIVE' make check

        # try to use source directory as a working directory
        - cd tests
        - cmake .
        - ctest -j$(nproc) --output-on-failure -LE EXPENSIVE

    artifacts:
        paths:
            # This directory subtree will be available for download
            # as an zip archive from given job log in GitLab.
            - "workdir/"
        expire_in: 1 month
        when: always
    tags:
        - docker

# Run selected Fedora release targets. The VERSION variable is
# used to determine the correct version of "rhcopr-toolset" repository.
build_31:
    image: fedora:31
    <<: *fedora
    variables:
        VERSION: "31"

build_32:
    image: fedora:32
    <<: *fedora
    variables:
        VERSION: "32"

build_rawhide:
    image: fedora:rawhide
    <<: *fedora
    variables:
        VERSION: "rawhide"
