.fedora: &fedora
    before_script:
        - curl -O --insecure https://password.corp.redhat.com/RH-IT-Root-CA.crt -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
        - update-ca-trust extract
    script:
        - dnf install dnf-plugins-core -y
        - dnf config-manager --add-repo https://copr.devel.redhat.com/coprs/rhcopr-project/toolset/repo/fedora-${VERSION}/rhcopr-project-toolset-fedora-${VERSION}.repo
        - dnf --enable-repo copr:copr.devel.redhat.com:rhcopr-project:toolset
        - sudo dnf install make rhcopr -y
        - sudo dnf copr enable lzaoral/Divine -y
        - sudo dnf copr enable redhat/acalabek/symbiotic -y
        - sudo dnf copr enable redhat/vmihalko/cbmc_utils -y
        - sudo dnf update -y
        - make install-deps
        - make configure
        - make check
    artifacts:
        paths:
            - "workdir/"
        expire_in: 1 month
        when: always
    tags:
        - docker

build_30:
    image: fedora:30
    script:
    <<: *rhcopr
    <<: *fedora
    variables:
        $VERSION: "30"

build_31:
    image: fedora:30
    <<: *rhcopr
    <<: *fedora
    variables:
        $VERSION: "31"
    
build_rawhide:
    image: fedora:rawhide
    <<: *rhcopr_rawhide
    <<: *fedora
    variables:
        $VERSION: "rawhide"